arch:
    max_epochs: 1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 55.0
datasets:
    augmentation:
        image_shape: (384, 1024)
    train:
        batch_size: 1
        dataset: ['KITTI']
        path: ['/cluster/home/takmaza/psfm/Sintel']
        split: ['alley_2.txt']
        depth_type: ['groundtruth']
        repeat: [40]
    validation:
        dataset: ['KITTI']
        path: ['/cluster/home/takmaza/psfm/Sintel']
        split: ['alley_2.txt']
        depth_type: ['groundtruth']
    test:
        dataset: ['KITTI']
        path: ['/cluster/home/takmaza/psfm/Sintel']
        split: ['alley_2.txt']
        depth_type: ['groundtruth']
